In [1]:
using Revise
using Pkg
Pkg.activate("../")
using Raven

 Activating environment at `~/REPOS/Raven.jl/Project.toml`


In [2]:
edges=Raven.readToFeTedges(open("../testdata/scl.edge","r"))

12500×12500 SparseArrays.SparseMatrixCSC{Float64,Int64} with 64950 stored entries:
  [2    ,     1]  =  0.1
  [6    ,     1]  =  0.1
  [26   ,     1]  =  0.1
  [1    ,     2]  =  0.1
  [3    ,     2]  =  0.1
  [7    ,     2]  =  0.1
  [27   ,     2]  =  0.1
  [2    ,     3]  =  0.1
  [4    ,     3]  =  0.1
  [8    ,     3]  =  0.1
  [28   ,     3]  =  0.1
  [3    ,     4]  =  0.1
  ⋮
  [12496, 12497]  =  0.1
  [12498, 12497]  =  0.1
  [12473, 12498]  =  0.1
  [12493, 12498]  =  0.1
  [12497, 12498]  =  0.1
  [12499, 12498]  =  0.1
  [12474, 12499]  =  0.1
  [12494, 12499]  =  0.1
  [12498, 12499]  =  0.1
  [12500, 12499]  =  0.1
  [12475, 12500]  =  0.1
  [12495, 12500]  =  0.1
  [12499, 12500]  =  0.1

In [3]:

import Pkg; Pkg.add("UnicodePlots")
import UnicodePlots
UnicodePlots.spy(edges)


   Updating registry at `~/.julia/registries/General`


   Updating git-repo `https://github.com/JuliaRegistries/General.git`


  Resolving package versions...
   Updating `~/REPOS/Raven.jl/Project.toml`
 [no changes]
   Updating `~/REPOS/Raven.jl/Manifest.toml`
 [no changes]


                      Sparsity Pattern
         ┌──────────────────────────────────────────┐    
       1 │⠻⣦⡀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀│ > 0
         │⠀⠈⠻⣦⡀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀│ < 0
         │⠀⠀⠀⠈⠻⣦⡀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀│    
         │⠀⠀⠀⠀⠀⠈⠻⣦⡀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀│    
         │⠀⠀⠀⠀⠀⠀⠀⠈⠻⣦⡀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀│    
         │⠀⠀⠀⠀⠀⠀⠀⠀⠀⠈⠻⣦⡀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀│    
         │⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠈⠻⣦⡀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀│    
         │⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠈⠻⣦⡀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀│    
         │⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠈⠻⣦⡀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀│    
         │⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠈⠻⣦⡀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀│    
         │⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠈⠻⣦⡀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀│    
         │⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠈⠻⣦⡀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀│    
         │⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠈⠻⣦⡀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀│    
         │⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠈⠻⣦⡀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀│    
         │⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠈⠻⣦⡀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀│    
         │⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀

In [4]:
"Single iteration of Yu's power iterative method to solve master equation. Needs a bare ratematrix."
function YuPRBpowm!(ω, P)
    Σ=sum # just for notation niceness
    for i in eachindex(P)
        P[i] = Σ(ω[i,:] .* P[:]) / Σ(ω[:,i]) / (1 - Σ( (ω[:,i].-ω[i,:]) .* P[:]) / Σ(ω[:,i]) ) 
    end
    P
end

YuPRBpowm!

In [5]:
ω=Raven.bareratematrix(edges,Raven.rateAdiabatic)
ω/=9.54587e13

12500×12500 SparseArrays.SparseMatrixCSC{Float64,Int64} with 64950 stored entries:
  [2    ,     1]  =  1.0
  [6    ,     1]  =  1.0
  [26   ,     1]  =  1.0
  [1    ,     2]  =  1.0
  [3    ,     2]  =  1.0
  [7    ,     2]  =  1.0
  [27   ,     2]  =  1.0
  [2    ,     3]  =  1.0
  [4    ,     3]  =  1.0
  [8    ,     3]  =  1.0
  [28   ,     3]  =  1.0
  [3    ,     4]  =  1.0
  ⋮
  [12496, 12497]  =  1.0
  [12498, 12497]  =  1.0
  [12473, 12498]  =  1.0
  [12493, 12498]  =  1.0
  [12497, 12498]  =  1.0
  [12499, 12498]  =  1.0
  [12474, 12499]  =  1.0
  [12494, 12499]  =  1.0
  [12498, 12499]  =  1.0
  [12500, 12499]  =  1.0
  [12475, 12500]  =  1.0
  [12495, 12500]  =  1.0
  [12499, 12500]  =  1.0

In [6]:
P=vcat(zeros(Int(ω.m/2)),ones(Int(ω.m/2)))

12500-element Array{Float64,1}:
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 ⋮
 1.0
 1.0
 1.0
 1.0
 1.0
 1.0
 1.0
 1.0
 1.0
 1.0
 1.0
 1.0

In [7]:
@time Raven.YuPRBpowm!(ω,P)

  1.054340 seconds (1.95 M allocations: 106.971 MiB, 1.53% gc time)


12500-element Array{Float64,1}:
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 ⋮
 1.0
 1.0
 1.0
 1.0
 1.0
 1.0
 1.0
 1.0
 1.0
 1.0
 1.0
 1.0

In [8]:
sum(abs.(vcat(zeros(Int(ω.m/2)),ones(Int(ω.m/2))).-P))

9.800000000000002

In [9]:
Raven.YuPRBpowm!(ω,P)

12500-element Array{Float64,1}:
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 ⋮
 1.0
 1.0
 1.0
 1.0
 1.0
 1.0
 1.0
 1.0
 1.0
 1.0
 1.0
 1.0

In [10]:
@time Raven.YuPRBpowm_converge!(ω,P, eps=1)

c = 1
c = 2
c = 3
c = 4
c = 5
c = 6
c = 7
c = 8
c = 9
c = 10
c = 11
c = 12
c = 13
c = 14
c = 15
c = 16
c = 17
c = 18
c = 19
c = 20
c = 21
c = 22
c = 23
c = 24
c = 25
c = 26
c = 27
c = 28
c = 29
c = 30
c = 31
c = 32
c = 33
c = 34
c = 35
c = 36
c = 37
c = 38
c = 39
c = 40
c = 41
 31.063379 seconds (13.87 M allocations: 1.037 GiB, 0.33% gc time)


41

In [11]:
@time Raven.YuPRBpowm_converge!(ω,P, eps=0.1)

c = 1
c = 2
c = 3
c = 4
c = 5
c = 6
c = 7
c = 8
c = 9
c = 10
c = 11
c = 12
c = 13
c = 14
c = 15
c = 16
c = 17
c = 18
c = 19
c = 20
c = 21
c = 22
c = 23
c = 24
c = 25
c = 26
c = 27
c = 28
c = 29
c = 30
c = 31
c = 32
c = 33
c = 34
c = 35
c = 36
c = 37
c = 38
c = 39
c = 40
c = 41
c = 42
c = 43
c = 44
c = 45
c = 46
c = 47
c = 48
c = 49
c = 50
c = 51
c = 52
c = 53
c = 54
c = 55
c = 56
c = 57
c = 58
c = 59
c = 60
c = 61
c = 62
c = 63
c = 64
c = 65
c = 66
c = 67
c = 68
c = 69
c = 70
c = 71
c = 72
c = 73
c = 74
c = 75
c = 76
c = 77
c = 78
c = 79
c = 80
c = 81
c = 82
c = 83
c = 84
c = 85
c = 86
c = 87
c = 88
c = 89
c = 90
c = 91
c = 92
c = 93
c = 94
c = 95
c = 96
c = 97
c = 98
c = 99
c = 100
c = 101
c = 102
c = 103
c = 104
c = 105
c = 106
c = 107
c = 108
c = 109
c = 110
c = 111
c = 112
c = 113
c = 114
c = 115
c = 116
c = 117
c = 118
c = 119
c = 120
c = 121
c = 122
c = 123
c = 124
c = 125
c = 126
c = 127
c = 128
c = 129
c = 130
c = 131
c = 132
c = 133
c = 134
c = 135
c = 136
c = 137
c = 138
c = 

InterruptException: InterruptException:

In [12]:
P

12500-element Array{Float64,1}:
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 ⋮
 1.0
 1.0
 1.0
 1.0
 1.0
 1.0
 1.0
 1.0
 1.0
 1.0
 1.0
 1.0

In [13]:
using SparseArrays
sP=sparse(P)

12500-element SparseVector{Float64,Int64} with 12175 stored entries:
  [326  ]  =  2.05013e-143
  [327  ]  =  2.20856e-166
  [328  ]  =  2.20856e-166
  [329  ]  =  2.20856e-166
  [330  ]  =  2.05013e-143
  [331  ]  =  2.20856e-166
  [332  ]  =  3.78577e-185
  [333  ]  =  3.78577e-185
  [334  ]  =  3.78577e-185
  [335  ]  =  2.20856e-166
           ⋮
  [12490]  =  1.0
  [12491]  =  1.0
  [12492]  =  1.0
  [12493]  =  1.0
  [12494]  =  1.0
  [12495]  =  1.0
  [12496]  =  1.0
  [12497]  =  1.0
  [12498]  =  1.0
  [12499]  =  1.0
  [12500]  =  1.0

In [14]:
@time sum(ω[1000,:])

  0.007951 seconds (329 allocations: 18.875 KiB)


3.999998863302724

In [15]:
@time sum(ω[10000,:] .* sP)

  0.051608 seconds (231.26 k allocations: 12.393 MiB)


3.999998863302724

In [16]:
p=copy(sP)/2
@time sum(p.=ω[10000,:] .* sP)

  0.071069 seconds (115.81 k allocations: 5.471 MiB)


3.999998863302724

In [17]:
@time SparseArrays.dot(ω[10000,:], sP)

  0.007586 seconds (275 allocations: 15.734 KiB)


3.999998863302724

In [18]:
⋅=SparseArrays.dot
@time ω[10000,:]⋅sP

  0.000068 seconds (6 allocations: 304 bytes)


3.999998863302724

In [19]:
@time ω[10000,:]⋅P

  0.019563 seconds (31.29 k allocations: 1.690 MiB, 44.97% gc time)


3.999998863302724

In [20]:
rates=Raven.ratematrix(edges,Raven.rateAdiabatic)

12500×12500 SparseMatrixCSC{Float64,Int64} with 77450 stored entries:
  [1    ,     1]  =  -2.86376e14
  [2    ,     1]  =  9.54587e13
  [6    ,     1]  =  9.54587e13
  [26   ,     1]  =  9.54587e13
  [1    ,     2]  =  9.54587e13
  [2    ,     2]  =  -3.81835e14
  [3    ,     2]  =  9.54587e13
  [7    ,     2]  =  9.54587e13
  [27   ,     2]  =  9.54587e13
  [2    ,     3]  =  9.54587e13
  [3    ,     3]  =  -3.81835e14
  [4    ,     3]  =  9.54587e13
  ⋮
  [12493, 12498]  =  9.54587e13
  [12497, 12498]  =  9.54587e13
  [12498, 12498]  =  -3.81835e14
  [12499, 12498]  =  9.54587e13
  [12474, 12499]  =  9.54587e13
  [12494, 12499]  =  9.54587e13
  [12498, 12499]  =  9.54587e13
  [12499, 12499]  =  -3.81835e14
  [12500, 12499]  =  9.54587e13
  [12475, 12500]  =  9.54587e13
  [12495, 12500]  =  9.54587e13
  [12499, 12500]  =  9.54587e13
  [12500, 12500]  =  -2.86376e14

In [21]:
YuPRBpowm!(rates, P)

12500-element Array{Float64,1}:
 NaN
 NaN
 NaN
 NaN
 NaN
 NaN
 NaN
 NaN
 NaN
 NaN
 NaN
 NaN
 NaN
   ⋮
 NaN
 NaN
 NaN
 NaN
 NaN
 NaN
 NaN
 NaN
 NaN
 NaN
 NaN
 NaN

In [ ]:
ρ=Raven.solveMasterDense(rates)

In [ ]:
ρ.Vt[:,1]

In [ ]:
sum(abs.(ρ.Vt[:,1]))

In [ ]:
import DelimitedFiles
raw=DelimitedFiles.readdlm(open("../testdata/scl.xyz","r"))

In [ ]:
XYZ=raw[:,1:3]

In [ ]:
xyz=Raven.readToFeTxyz(open("../testdata/scl.xyz","r"))

In [ ]:
1+!